from typing import Dict, Any, Optional

from pydantic import BaseModel, Field


class KeystoreProfile(BaseModel):
    """
    Contact information for the keystore.
    """
    name: str = Field(..., title="Name", description="The contact name.", examples=["Foo Bar"])
    email: str = Field(..., title="Email", description="The contact email address.", examples=["foo.bar@somehwere.com"])


class KeystoreContent(BaseModel):
    """
    The content of a keystore.
    """
    iid: str = Field(..., title="IId", description="The id of the keystore's identity.")
    profile: KeystoreProfile = Field(..., title="Profile", description="The profile of the keystore.")
    nonce: int = Field(..., title="Nonce", description="A positive integer value that is increased every time the keystore content is updated.", examples=[4])
    signature: str = Field(..., title="Signature", description="A signature made with the keystore identity's signing key. This signature is used to verify the integrity of the keystore content.")
    assets: Dict[str, Any] = Field(..., title="Assets", description="Assets contained by this keystore.")


class GithubCredentials(BaseModel):
    """
    Github credentials.
    """
    login: str = Field(..., title="Login", description="The login name.")
    personal_access_token: str = Field(..., repr=False, title="Personal Access Token", description="The personal access token generated by Github.")

    def __repr__(self) -> str:
        return f"GithubCredentials(login={self.login!r}, personal_access_token=<redacted>)"


class SSHCredentials(BaseModel):
    """
    SSH credentials.
    """
    host: str = Field(..., title="Host", description="The host name or IP of the remote machine.", examples=["35.34.55.2"])
    login: str = Field(..., title="Login", description="The login for the remote machine.")
    key: str = Field(..., repr=False, title="Key", description="The key content.")
    passphrase: Optional[str] = Field(repr=False, title="Passphrase", description="An optional passphrase in case the key is protected.")

    def __repr__(self) -> str:
        return f"SSHCredentials(host={self.host!r}, login={self.login!r}, key=<redacted>, passphrase=<redacted>)"
